# Change baseurl before deploy
baseURL = "https://airGuitarX.github.io/"
theme = "hugo-theme-stack"
languageCode = "en-us"
title = "玉米地"
enableRobotsTXT = true

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "cornfieldrr"

[pagination]
pagerSize = 5

disableHugoGeneratorInject = true

# Cache location
[caches]
  [caches.images]
    dir = ':cacheDir/images'